### ISSUE TITLE
default precision

### ISSUE THREAD

**Issue by daydaymoyu** [alemart/speedy-vision#25]
Hi
   I met a problem when using the fast detector in this demo. It shows
```
WebGL error. Can't create shader.

-------- ERROR ------
no default precision defined for variable 'vec4[9]'
```

test device is HuaWei mate10, Android, the CPU is Kirin 970, browser is chrome 97. 
So where to add the precision?
thanks!

**Comment by alemart** [comment]
Hi,

Please post the entire error message and a minimal code example that reproduces the error.

**Comment by daydaymoyu** [comment]
> 

Hi

the code example is [here](https://alemart.github.io/speedy-vision/demos/image-features.html)

and the entire error message is
```
utils.js:77 [speedy-vision] Speedy Vision v0.9.0-wip-dev. GPU-accelerated Computer Vision for JavaScript by Alexandre Martins. https://github.com/alemart/speedy-vision
utils.js:77 [speedy-vision] Loaded SpeedyMedia with a [object HTMLImageElement].
utils.js:77 [speedy-vision] Creating a default WebGL2 rendering context...
utils.js:77 [speedy-vision] The WebAssembly routines have been loaded!
speedy-program.js:445 Uncaught (in promise) GLError: WebGL error. Can't create shader.

---------- ERROR ----------
0:59: S0032: no default precision defined for variable 'vec4[9]'

program not linked

---------- SOURCE CODE ----------
  1. #version 300 es
  2. 
  3. #if !(0)
  4. precision mediump float; 
  5. precision mediump sampler2D;
  6. precision highp int; 
  7. #endif
  8. 
  9. #if 0 == 0
 10. #define OUT_TYPE mediump vec4
 11. #elif 0 == 1
 12. #define OUT_TYPE mediump ivec4
 13. #elif 0 == 2
 14. #define OUT_TYPE mediump uvec4
 15. #else
 16. #error Unknown FS_OUTPUT_TYPE
 17. #endif
 18. 
 19. out OUT_TYPE color;
 20. in highp vec2 texCoord;
 21. uniform highp vec2 texSize;
 22. #ifndef _GLOBAL_GLSL
 23. #define _GLOBAL_GLSL
 24. #define threadLocation() ivec2(texCoord * texSize)
 25. #define outputSize() ivec2(texSize)
 26. #define threadPixel(img) textureLod((img), texCoord, 0.0f)
 27. #define pixelAt(img, pos) texelFetch((img), (pos), 0)
 28. #define pixelAtShortOffset(img, offset) textureLodOffset((img), texCoord, 0.0f, (offset))
 29. #define pixelAtLongOffset(img, offset) textureLod((img), texCoord + vec2(offset) / texSize, 0.0f)
 30. #endif
 31. #ifndef _PYRAMIDS_GLSL
 32. #define _PYRAMIDS_GLSL
 33. #define pyrPixel(pyr, lod) textureLod((pyr), texCoord, (lod))
 34. #define pyrPixelAtOffset(pyr, lod, pot, offset) textureLod((pyr), texCoord + ((pot) * vec2(offset)) / texSize, (lod))
 35. #define pyrPixelAt(pyr, pos, lod) textureLod((pyr), (vec2(pos) + vec2(0.5f)) / texSize, (lod))
 36. #define pyrPixelAtEx(pyr, pos, lod, pyrBaseSize) textureLod((pyr), (vec2(pos) + vec2(0.5f)) / vec2(pyrBaseSize), (lod))
 37. #define pyrSubpixelAtEx(pyr, pos, lod, pyrBaseSize) textureLod((pyr), ((pos) + vec2(0.5f)) / vec2(pyrBaseSize), (lod))
 38. #define pyrSubpixelAtExOffset(pyr, pos, lod, pot, offset, pyrBaseSize) textureLod((pyr), (((pos) + vec2(0.5f)) + ((pot) * vec2(offset))) / vec2(pyrBaseSize), (lod))
 39. const int PYRAMID_MAX_LEVELS = int(8);
 40. const float F_PYRAMID_MAX_LEVELS = float(8);
 41. const float LOG2_PYRAMID_MAX_SCALE = float(0);
 42. #define encodeLod(lod) ((LOG2_PYRAMID_MAX_SCALE + (lod)) / (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS))
 43. float decodeLod(float encodedLod)
 44. {
 45. float lod = encodedLod * (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS) - LOG2_PYRAMID_MAX_SCALE;
 46. return lod - lod * step(1.0f, encodedLod);
 47. }
 48. #define LOD_EPS 0.0625f
 49. const float ENCODED_LOD_EPS = (LOD_EPS / (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS));
 50. #define isSameLod(lod1, lod2) (abs((lod1) - (lod2)) < LOD_EPS)
 51. #define isSameEncodedLod(alpha1, alpha2) (abs((alpha1) - (alpha2)) < ENCODED_LOD_EPS)
 52. #endif
 53. #ifndef _FLOAT16_GLSL
 54. #define _FLOAT16_GLSL
 55. #define encodeFloat16(f) (vec2(packf16(f)) / 255.0f)
 56. #define decodeFloat16(v) unpackf16(uvec2((v) * 255.0f))
 57. #define encodePairOfFloat16(f) vec4(encodeFloat16((f).x), encodeFloat16((f).y))
 58. #define decodePairOfFloat16(v) vec2(decodeFloat16((v).rg), decodeFloat16((v).ba))
 59. #define encodeNullPairOfFloat16() vec4(1.0f)
 60. #define isNullPairOfFloat16(v) all(equal((v), encodeNullPairOfFloat16()))
 61. #define encodeDiscardedPairOfFloat16() vec4(0.0f, 1.0f, 0.0f, 1.0f)
 62. #define isDiscardedPairOfFloat16(v) all(equal((v), encodeDiscardedPairOfFloat16()))
 63. #define encodeFloat16NaN() vec2(0.5f, 1.0f)
 64. #define isEncodedFloat16NaN(v) all(equal((v), encodeFloat16NaN()))
 65. uvec2 packf16( float f)
 66. {
 67. uint y = packHalf2x16(vec2(f, 0.0f));
 68. return uvec2(y, y >> 8u) & 0xFFu;
 69. }
 70. float unpackf16(uvec2 v)
 71. {
 72. v &= 0xFFu;
 73. return unpackHalf2x16(v.x | (v.y << 8u)).x;
 74. }
 75. bool isEncodedFloat16Zero(vec2 v)
 76. {
 77. uvec2 w = uvec2(v * 255.0f);
 78. return 0u == w.x + w.y * (0x80u - w.y);
 79. }
 80. #endif
 81. uniform sampler2D corners;
 82. void main()
 83. {
 84. ivec2 thread = threadLocation();
 85. vec4 pixel = threadPixel(corners);
 86. float encodedLod = pixel.a;
 87. float score = decodeFloat16(pixel.rb);
 88. float lod = decodeLod(encodedLod);
 89. float pot = exp2(lod);
 90. color = pixel;
 91. if(score == 0.0f)
 92. return;
 93. #if 1
 94. vec2 gridSize = vec2(pot);
 95. vec2 gridLocation = floor(mod(texCoord * texSize, gridSize));
 96. vec2 gridDelta = gridLocation / gridSize - vec2(0.5f);
 97. float gridStep = 1.0f / pot;
 98. const float adjustment = 1.25f;
 99. color.rb = encodeFloat16(0.0f);
100. if(max(abs(gridDelta.x), abs(gridDelta.y)) > adjustment * gridStep)
101. return;
102. #endif
103. #define P(x,y) textureLod(corners, texCoord + pot * vec2((x), (y)) / texSize, 0.0f)
104. vec4 pix[9] = vec4[9](
105. P(-1,-1), P(0,-1), P(1,-1),
106. P(-1,0), pixel, P(1,0),
107. P(-1,1), P(0,1), P(1,1)
108. );
109. #define S(j) decodeFloat16(pix[j].rb)
110. mat3 scores = mat3(
111. S(0), S(1), S(2),
112. S(3), S(4), S(5),
113. S(6), S(7), S(8)
114. );
115. #define B(j) float(isSameLod(decodeLod(pix[j].a), lod))
116. mat3 sameLod = mat3(
117. B(0), B(1), B(2),
118. B(3), B(4), B(5),
119. B(6), B(7), B(8)
120. );
121. mat3 sameLodScores = matrixCompMult(scores, sameLod);
122. vec3 maxScore3 = max(sameLodScores[0], max(sameLodScores[1], sameLodScores[2]));
123. float maxScore = max(maxScore3.x, max(maxScore3.y, maxScore3.z));
124. color.rb = encodeFloat16(score * step(maxScore, score));
125. }
-> [speedy-vision.js]
    at Function._compile (speedy-program.js:445)
    at SpeedyProgram._init (speedy-program.js:110)
    at new SpeedyProgram (speedy-program.js:81)
    at SpeedyProgramGroupKeypoints._createProgram (speedy-program-group.js:137)
    at SpeedyProgramGroupKeypoints.Object.defineProperty.get (speedy-program-group.js:101)
    at SpeedyPipelineNodeHarrisKeypointDetector._run (harris.js:143)
    at SpeedyPipelineNodeHarrisKeypointDetector.execute (pipeline-node.js:174)
    at Function._runSequence (pipeline.js:190)
    at SpeedyPipeline.run (pipeline.js:160)
    at update (image-features.html:88)
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 ()

```

**Comment by alemart** [comment]
Thanks for your feedback.

This may be a driver bug.

Are you able to build Speedy Vision on your machine and run it locally with `npm start` ?

**Comment by daydaymoyu** [comment]
> 

OK. I will try later.

**Comment by deep-ar** [comment]
Hello! I have the same error on feature-matching example


-------------------------
Uncaught (in promise) GLError: WebGL error. 

---------- ERROR ----------

0:59: S0032: no default precision defined for variable 'vec4[9]'
program not linked
---------- SOURCE CODE ----------

  1. #version 300 es
  2. 
  3. #if 0 == 0
  4. precision mediump float; 
  5. precision mediump sampler2D;
  6. precision highp int; 
  7. #endif
  8. 
  9. #if 0 == 0
 10. #define OUT_TYPE mediump vec4
 11. #elif 0 == 1
 12. #define OUT_TYPE mediump ivec4
 13. #elif 0 == 2
 14. #define OUT_TYPE mediump uvec4
 15. #else
 16. #error Unknown FS_OUTPUT_TYPE
 17. #endif
 18. 
 19. out OUT_TYPE color;
 20. in highp vec2 texCoord;
 21. uniform highp vec2 texSize;
 22. #ifndef _GLOBAL_GLSL
 23. #define _GLOBAL_GLSL
 24. #define threadLocation() ivec2(texCoord * texSize)
 25. #define outputSize() ivec2(texSize)
 26. #define threadPixel(img) textureLod((img), texCoord, 0.0f)
 27. #define pixelAt(img, pos) texelFetch((img), (pos), 0)
 28. #define pixelAtShortOffset(img, offset) textureLodOffset((img), texCoord, 0.0f, (offset))
 29. #define pixelAtLongOffset(img, offset) textureLod((img), texCoord + vec2(offset) / texSize, 0.0f)
 30. #endif
 31. #ifndef _PYRAMIDS_GLSL
 32. #define _PYRAMIDS_GLSL
 33. #define pyrPixel(pyr, lod) textureLod((pyr), texCoord, (lod))
 34. #define pyrPixelAtOffset(pyr, lod, pot, offset) textureLod((pyr), texCoord + ((pot) * vec2(offset)) / texSize, (lod))
 35. #define pyrPixelAt(pyr, pos, lod) textureLod((pyr), (vec2(pos) + vec2(0.5f)) / texSize, (lod))
 36. #define pyrPixelAtEx(pyr, pos, lod, pyrBaseSize) textureLod((pyr), (vec2(pos) + vec2(0.5f)) / vec2(pyrBaseSize), (lod))
 37. #define pyrSubpixelAtEx(pyr, pos, lod, pyrBaseSize) textureLod((pyr), ((pos) + vec2(0.5f)) / vec2(pyrBaseSize), (lod))
 38. #define pyrSubpixelAtExOffset(pyr, pos, lod, pot, offset, pyrBaseSize) textureLod((pyr), (((pos) + vec2(0.5f)) + ((pot) * vec2(offset))) / vec2(pyrBaseSize), (lod))
 39. const int PYRAMID_MAX_LEVELS = int(8);
 40. const float F_PYRAMID_MAX_LEVELS = float(8);
 41. const float LOG2_PYRAMID_MAX_SCALE = float(0);
 42. #define encodeLod(lod) ((LOG2_PYRAMID_MAX_SCALE + (lod)) / (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS))
 43. float decodeLod(float encodedLod)
 44. {
 45. float lod = encodedLod * (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS) - LOG2_PYRAMID_MAX_SCALE;
 46. return lod - lod * step(1.0f, encodedLod);
 47. }
 48. #define LOD_EPS 0.0625f
 49. const float ENCODED_LOD_EPS = (LOD_EPS / (LOG2_PYRAMID_MAX_SCALE + F_PYRAMID_MAX_LEVELS));
 50. #define isSameLod(lod1, lod2) (abs((lod1) - (lod2)) < LOD_EPS)
 51. #define isSameEncodedLod(alpha1, alpha2) (abs((alpha1) - (alpha2)) < ENCODED_LOD_EPS)
 52. #endif
 53. #ifndef _FLOAT16_GLSL
 54. #define _FLOAT16_GLSL
 55. #define encodeFloat16(f) (vec2(packf16(f)) / 255.0f)
 56. #define decodeFloat16(v) unpackf16(uvec2((v) * 255.0f))
 57. #define encodePairOfFloat16(f) vec4(encodeFloat16((f).x), encodeFloat16((f).y))
 58. #define decodePairOfFloat16(v) vec2(decodeFloat16((v).rg), decodeFloat16((v).ba))
 59. #define encodeNullPairOfFloat16() vec4(1.0f)
 60. #define isNullPairOfFloat16(v) all(equal((v), encodeNullPairOfFloat16()))
 61. #define encodeDiscardedPairOfFloat16() vec4(0.0f, 1.0f, 0.0f, 1.0f)
 62. #define isDiscardedPairOfFloat16(v) all(equal((v), encodeDiscardedPairOfFloat16()))
 63. #define encodeFloat16NaN() vec2(0.5f, 1.0f)
 64. #define isEncodedFloat16NaN(v) all(equal((v), encodeFloat16NaN()))
 65. uvec2 packf16( float f)
 66. {
 67. uint y = packHalf2x16(vec2(f, 0.0f));
 68. return uvec2(y, y >> 8u) & 0xFFu;
 69. }
 70. float unpackf16(uvec2 v)
 71. {
 72. v &= 0xFFu;
 73. return unpackHalf2x16(v.x | (v.y << 8u)).x;
 74. }
 75. bool isEncodedFloat16Zero(vec2 v)
 76. {
 77. uvec2 w = uvec2(v * 255.0f);
 78. return 0u == w.x + w.y * (0x80u - w.y);
 79. }
 80. #endif
 81. uniform sampler2D corners;
 82. void main()
 83. {
 84. ivec2 thread = threadLocation();
 85. vec4 pixel = threadPixel(corners);
 86. float encodedLod = pixel.a;
 87. float score = decodeFloat16(pixel.rb);
 88. float lod = decodeLod(encodedLod);
 89. float pot = exp2(lod);
 90. color = pixel;
 91. if(score == 0.0f)
 92. return;
 93. #if 1
 94. vec2 gridSize = vec2(pot);
 95. vec2 gridLocation = floor(mod(texCoord * texSize, gridSize));
 96. vec2 gridDelta = gridLocation / gridSize - vec2(0.5f);
 97. float gridStep = 1.0f / pot;
 98. const float adjustment = 1.25f;
 99. color.rb = encodeFloat16(0.0f);
100. if(max(abs(gridDelta.x), abs(gridDelta.y)) > adjustment * gridStep)
101. return;
102. #endif
103. #define P(x,y) textureLod(corners, texCoord + pot * vec2((x), (y)) / texSize, 0.0f)
104. vec4 pix[9] = vec4[9](
105. P(-1,-1), P(0,-1), P(1,-1),
106. P(-1,0), pixel, P(1,0),
107. P(-1,1), P(0,1), P(1,1)
108. );
109. #define S(j) decodeFloat16(pix[j].rb)
110. mat3 scores = mat3(
111. S(0), S(1), S(2),
112. S(3), S(4), S(5),
113. S(6), S(7), S(8)
114. );
115. #define B(j) float(isSameLod(decodeLod(pix[j].a), lod))
116. mat3 sameLod = mat3(
117. B(0), B(1), B(2),
118. B(3), B(4), B(5),
119. B(6), B(7), B(8)
120. );
121. mat3 sameLodScores = matrixCompMult(scores, sameLod);
122. vec3 maxScore3 = max(sameLodScores[0], max(sameLodScores[1], sameLodScores[2]));
123. float maxScore = max(maxScore3.x, max(maxScore3.y, maxScore3.z));
124. color.rb = encodeFloat16(score * step(maxScore, score));
125. }

-> [speedy-vision.js]
    at Function._compile (speedy-program.js:451:1)
    at SpeedyProgram._init (speedy-program.js:110:1)
    at new SpeedyProgram (speedy-program.js:81:1)
    at SpeedyProgramGroupKeypoints._createProgram (speedy-program-group.js:137:1)
    at SpeedyProgramGroupKeypoints.Object.defineProperty.get (speedy-program-group.js:101:1)
    at SpeedyPipelineNodeHarrisKeypointDetector._run (harris.js:143:1)
    at SpeedyPipelineNodeHarrisKeypointDetector.execute (pipeline-node.js:174:1)
    at Function._runSequence (pipeline.js:212:1)
    at SpeedyPipeline.run (pipeline.js:169:1)
    at window.onload (feature-matching.html:66:55)

**Comment by alemart** [comment]
Hi @deep-ar,

Seems like a driver bug. Can you tell me what is your device and GPU?

Are you able to add an explicit precision qualifier to that specific variable?

**Comment by deep-ar** [comment]
well, fixed this by changing nonmax-space.glsl:
#define P(x,y) textureLod(corners, texCoord + pot * vec2((x), (y)) / texSize, 0.0f)
    /*vec4 pix[9] = vec4[9](
        P(-1,-1), P(0,-1), P(1,-1),
        P(-1,0), pixel, P(1,0),
        P(-1,1), P(0,1), P(1,1), P(1,1)
    );*/
    vec4 pix[9];
    pix[0] = P(-1,-1);
    pix[1] = P(0,-1);
    pix[2] = P(1,-1);
    pix[3] = P(-1,0);
    pix[4] = pixel;
    pix[5] = P(1,0);
    pix[6] = P(-1,1);
    pix[7] = P(0,1);
    pix[8] = P(1,1);
    
    
    It seems some problem with array constructors in mobile shaders

**Comment by alemart** [comment]
> It seems some problem with array constructors in mobile shaders

@deep-ar Interesting finding! Is the feature matching demo working in your mobile device now? Do you see the matches?

**Comment by deep-ar** [comment]
Yes. Now it works fine on android, On iOS it doen't find matches. I'm trying to understand why

**Comment by deep-ar** [comment]
could you help me to debug it? I've found that found features works fine on iOS, but not matching not optical flow doesn't show results. result arrays are empty. It seems some step fails. How can I identify what exact step fails? Is there an option to track data after each step?

**Comment by alemart** [comment]
@deep-ar There is a way to inspect data throughout the pipeline, but you'll only see bits and bytes. That's how it's designed.

Different results may be caused by differences in video drivers. This is a pain point. I am unable to debug the demos because I don't have the same devices you do.

I can help you debug, but it may take a few days. Would you be willing to do it? Also, would you tell me what your devices are, specifically?

Do the matches it finds on your Android device correspond to the matches it finds on your PC? If not, do the matches seem correct in both cases?
