### ISSUE TITLE
unequal placement of keypoints

### ISSUE THREAD

**Issue by under-score** [alemart/speedy-vision#36]
I am wondering why there is such an unequal placement of keypoints in the upper half of the image only?
See quick demo at shorturl.at/pMT06

**Comment by alemart** [comment]
> See quick demo at shorturl.at/pMT06

This URL redirects to a URL Shortener page, not to a demo, but I have a sense of what you may be referring to.

Do you have more than ~2000 keypoints? If so, decrease the sensitivity of the detector and/or increase its capacity.

https://github.com/alemart/speedy-vision#speedykeypointdetectorfast
https://github.com/alemart/speedy-vision#speedykeypointdetectorharris

**Comment by under-score** [comment]
thank you - sorry for the wrong link. Next try is https://bit.ly/3xHwndL
Setting different Harris parameter helps a bit while the distribution is still unequal.

**Comment by alemart** [comment]
Thanks for the new link. The uneven distribution of keypoints in your demo is expected.

If you would allow a suggestion: detect keypoints in each image separately and match them afterwards.

Why does it happen: there is a bias. Keypoints are found by means of a corner response function. The input of your program is a single image featuring text and other images. If you use that input in the [feature detection in an image](https://alemart.github.io/speedy-vision/demos/image-features.html) demo, you'll see that the detector responds more strongly (as expected) to the borders of the text and to corners near the empty space - hence the uneven distribution. The feature matching demo will then filter these keypoints and only the best matches will be displayed.

![Captura de tela_2022-06-12_19-11-16](https://user-images.githubusercontent.com/221477/173255725-5dc32c2d-b548-4903-a85d-1d499f0be856.png)

**Comment by under-score** [comment]
Agree with all you said, will run segmentation first. 
BTW drop the image above to avoid copyright issues...

**Comment by alemart** [comment]
OK. Do you have any other questions?

**Comment by alemart** [comment]
Feel free to reach out again if you have any questions.
