### ISSUE TITLE
Feature matching showing error in for loop.

### ISSUE THREAD

**Issue by nurulalamador** [alemart/speedy-vision#37]
I am trying to implement Feature matching in for loop but it's showing this error in some loop steps: 

```
Uncaught (in promise) OutOfMemoryError: Out of memory. Exhausted pool (capacity: 1024)
-> [speedy-vision.js]
    at SpeedyTexturePool.allocate (speedy-vision.js:1297:7)
    at SpeedyPipelineNodeImageSource._allocateWorkTextures (speedy-vision.js:1852:30)
    at SpeedyPipelineNodeImageSource.init (speedy-vision.js:1835:58)
    at SpeedyPipeline.init (speedy-vision.js:1929:19)
    at createPipeline (fontlist2.html:327:14)
    at image2.onload (fontlist2.html:178:25)
```

There are no problems with using tracking.js feature matching in for loop but speedy-vission feature detection is so much better than tracking.js image feature detection that's why I want to use speedy-vission, but facing that problem. 

I think I should do something inside `createPipeline()` function to solve out of memory problem, but what should I do?

**Comment by alemart** [comment]
How large is your pipeline?

If you're able to share some code, it helps.

**Comment by alemart** [comment]
Although increasing the capacity of the texture pool is a possibility, this may or may not be an efficient solution to your particular issue, depending on your pipeline and on your goals.

Feel free to reach out again if I may be of help to you.
