### ISSUE TITLE
Camera pose estimation from homography matrix

### ISSUE THREAD

**Issue by derfabse** [alemart/speedy-vision#39]
Hi, thanks for this fantastic library.
I was wondering if there is a way to estimate the camera pose (camera drift between two frames) from the homography matrix for SLAM.

**Comment by alemart** [comment]
> Hi, thanks for this fantastic library.

Thank you for your comment.

> I was wondering if there is a way to estimate the camera pose (camera drift between two frames) from the homography matrix for SLAM.

Even though the library doesn't provide camera routines at this time, you can estimate the pose using a planar homography if you have a calibrated camera. The following reference discusses the subject:

Marchand, E., Uchiyama, H., & Spindler, F. (2015). Pose estimation for augmented reality: a hands-on survey. IEEE transactions on visualization and computer graphics, 22(12), 2633-2651.
