### ISSUE TITLE
I've a really big issue with what youve done

### ISSUE THREAD

**Issue by Charliebaby019** [alemart/speedy-vision#41]
1. HOW did i miss this over the course of 3 months?

2. WHO allowed you to do this, without supervision?

3. WHY Dont i see 104 TONS of stars on this repository?

YOU.... are my hero. 
This is exacty what Ive been looking for for... years man. years.

oh, by the way mr smarty pants....
since we're talkin js vision challanges.....
you happen to know any solutions for depth estimation in javascript (without AI, without ARcore, monocular only..... and lets go for live too, and something different besides opencv opticla flow )
even if you dont feel like answering that one.....
i really just wanted to thank you for all your work

this is truly a work of art sir.
thank you

**Comment by Charliebaby019** [comment]
and sorry. this is just a really handy way to assure i can get positive messages to people .....
through the problems sections........

 humans are weird that way huh? 
 (and we wonder why it seems everyone complains so much in this world)

**Comment by Charliebaby019** [comment]
omg. 
just slid through your demos.....

this is SO BEYOND a work of art Sir.....
its like a miracle.

I dont have much.
im not in this commercially. 
and i can't sponsor you....

but i really wanna repay you, for your time and effort
paypal?
cash app?
fansonly?
anything. you let me know and i will buy you a bunch of coffees. not like a ton... but more than you have now

**Comment by Charliebaby019** [comment]
wait... are you saying......

i could just .....
ad any refrence image webp??
at anytime, and it will just track and find its pose.....
no training?
dynamic fudicial markers?

**Comment by Charliebaby019** [comment]
I was just looking at the basic ar app. and was aquainting myself with the three js  structure you have there... did not make it modify the tracker yet though, but im thinking as long as 

await tracker.database.add([{
            name: 'my-reference-image',
            image: document.getElementById('my-reference-image')
        }]);
        
        oh... once the session is started, trackers cant be updated?
        
        .. i just need to relax and look over your code some more first.
        
        BUT YEAH....... no... no no.
        I've been doing this myself for two years now. I hate ARcore and ARkit... andjust now accepting AI getting involved, but ive been dead set and determined....
         6dof is possible on any monoculare system with iIMUs and GPS under the right (even if low quality) JS library (and openCV or JSfeat ... but add web assembly now. anything should be possible
        and once 6dof, is achieved, landmarks fall into place. and then...... depth Estimation... and point registration.......
         anyhow... its really alot to manage. especially for me.... because before this... i didnt even bother with JS.
         
         irrelavant......
         i sat there one day and heard someone say.....
         VR will get better one day. it just needs to grow and then youll have what youve always wanted.
         and i nearly threw up.
         1. the technologies are here and they arent really headset dependent.
         they just need to accessible . so.... Javascript it is. no matter what.
         2. when do WE ever just sit there and wait for someone else to bring us our own dreams?

but remember..... i do not know... javascript. lol
and that makes me ALMOST.... completely useless.

and ive asked the same question...... am i going to make an impact? anywhere?
im pretty sure that answer is no..... EXCEPT in two places......
1. in my own experience, knowledge and growth..... its become who i am. Determined. Positive.(regadless of my ignorance)
2. .and..... in YOUr own experience....

i i...... i just think i know very much how you feel....
and we're both probably right. this all probably means so much more to us... than anyone out there.
but like i keep telling myself... i cant predict the future...i cant see the bigger picture from here....
but i know if i give this up......I'm giving up what COULD arrise from it
and im simply giving up on myself.



oh.... HOLOPORTATION.... that was actually a huge goal of mine....
and i knocked that out with 2 kinects and p5.js. and three.js.. in my first 3 months.
streams live through WEBRTC into a cardboard headset  I'd say (almost) perfectly 



just looking for the right 6dof tracking AR system to project it into 

oh... this.
slipping this into web assemply.....i think this could be the god like experience right here.
https://www.youtube.com/watch?v=vB_F-Sj0AX0



https://www.youtube.com/watch?v=Tn0JOVpFWzM
(and might as well enhance it with some spatial mapping )

professional full 3d teleprecensing. thats what we need. on everyones phone       (my dream)
!!!

ideas..... inspiration ...... hope.
https://www.youtube.com/watch?v=A_KnsMY_smQ
dont give up.
I love your work. always will now.

**Comment by alemart** [comment]
Yes, I do understand that some very cool things are possible with this library. This work is complex and challenging, and it takes more than being determined and positive, though.

If you have questions about AR, I ask you to [open an issue in the other repository](https://github.com/alemart/martins-js/issues) instead. Thank you.

**Comment by alemart** [comment]
> dont give up.

By the way, I am not giving up on anything, but I am doing things in my time and keeping things within my means.

I am closing this issue. Thank you for your message, and please let me know if you need any further help.
