### ISSUE TITLE
Optical Flow demo error.

### ISSUE THREAD

**Issue by mmadaria** [alemart/speedy-vision#42]
First of all, I would like to thank the creator of this project for his excellent work :)

Along with this, I have been testing the "Optical Flow" demo using Google Chrome v.108.0.5359.125 (Official Build) (64 bits), and when  I click over a person in the video the demo stops, showing the following error on the console :

**Uncaught TypeError: Cannot read properties of undefined (reading 'x')
     at renderFlowVectors (optical-flow.html:307:41)
     at render(optical-flow.html:219:17)**

What could be happening? It seems that this problem does not occur in Mozilla Firefox..

Regards,

Milko.

![optical-flow-demo-error](https://user-images.githubusercontent.com/8931581/209566462-d04ae6f7-6c58-4b50-9e6c-d0486c5b0178.png)

**Comment by alemart** [comment]
Hi Milko,

Thank you for your compliment. I appreciate it.

I will look into it.
