### ISSUE TITLE
LSH demo

### ISSUE THREAD

**Issue by under-score** [alemart/speedy-vision#48]
would be great if we could have also a LSH version of https://github.com/alemart/speedy-vision/blob/master/demos/feature-matching.html that shows how to combine keypoint batches into one LSH table and run a query.
Could that table also be produced offline eg from Python CV2 / ORB?
Thank you.

**Comment by alemart** [comment]
Thank you for your suggestion. I'm adding it to my TODO list. I'll leave this issue open for now.

> Could that table also be produced offline eg from Python CV2 / ORB?

`StaticLSHTables` is something I've invented myself - for Speedy and the GPU. OpenCV has FLANN-based feature matching methods, though the implementations differ.

`StaticLSHTables` is fed with an array of keypoints. It only has an output port, which is meant to be connected to a `LSHKNN` node.

**Comment by alemart** [comment]
We now have a LSH feature matching demo available.

**Comment by under-score** [comment]
thank you!
