### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by under-score** [alemart/speedy-vision#49]
I have rewritten the [LSH Feature Mapping](https://alemart.github.io/speedy-vision/demos/feature-matching-lsh.html) for my own purpose. After testing of 8 or 10 (matchingMedia) images against the pretested set
```
const matchingPipeline = createMatchingPipeline(combinedTrainingKeypoints, matchingMedia);
const result = await matchingPipeline.run();
```
it crashes with this error.

![Bildschirmfoto 2023-10-11 um 09 06 01](https://github.com/alemart/speedy-vision/assets/2796454/4db4e8df-bd7e-4125-9b09-abf166a1f41f)

Anything I could do?

**Comment by alemart** [comment]
Yes. Open src/gpu/speedy-texture-pool.js and change the `DEFAULT_CAPACITY` from 1024 to a larger value such as 2048. Run `npm run build` to generate a new .js file and try again.

In addition, make your pipeline leaner if possible. In my demo, I created one training pipeline for each training image for the sake of simplicity and didactics. It would be more economical to train with a single pipeline instead. I can help you with that if you need it.

**Comment by alemart** [comment]
May I be of further help?

**Comment by alemart** [comment]
Glad to know it's solved!
