### ISSUE TITLE
forward-backward optical flow with lucas-kanade

### ISSUE THREAD

**Issue by Phillip-Thomas** [alemart/speedy-vision#50]
Hi, I am trying to implement forward-backward optical flow for use in a browser based SLAM engine. After reviewing the documentation, I don't see any explicit functionality for achieving this goal but there is mention of bidirectional optical flow in the "Speedy.Keypoint.DistanceFilter()" section.

I am curious if there are any examples of this sort of implementation anywhere and if not, any advice on the best way to approach the problem? I will gladly contribute a demo myself once I have it operational!

**Comment by alemart** [comment]
> there is mention of bidirectional optical flow in the "Speedy.Keypoint.DistanceFilter()" section.

The idea is that you can track the keypoints twice. After tracking them, track them again with a reversed flow of time and use the distance filter to discard spurious matches.

There is example code of the distance filter in the unit tests.

> I am curious if there are any examples of this sort of implementation anywhere

I'm approaching computer vision in an original way with Speedy Vision. To the best of my knowledge, there is not anything quite like it anywhere :)
